local NewUserRewardDef = {
    GR_NEWUSERREWARD_QUERY_REWARDSTATE      = 402801,
    GR_NEWUSERREWARD_TAKE_REWARD            = 402802,

    NEWUSERREWARD_ITEMTYPE_SILVER           = 1, -- 银子
    NEWUSERREWARD_ITEMTYPE_EXCHANGE         = 2, -- 兑换券
    NEWUSERREWARD_ITEMTYPE_PROP             = 3, -- 道具

    REWARD_PROP_ID_ONEDAY_CARD_MARKER       = 3, -- 道具ID：1天记牌器
    REWARD_PROP_ID_EXPRESSION_ROSE          = 6, -- 道具ID：表情玫瑰
    REWARD_PROP_ID_EXPRESSION_LIGHTNING     = 7, -- 道具ID：表情闪电
    REWARD_PROP_ID_ONEBOUT_CARDMARKER       = 8, -- 道具ID：单局记牌器
    REWARD_PROP_ID_TIMING_GAME_TICKET       = 17, -- 道具ID：定时赛门票

    NEWUSERREWARD_REWARDSTATE_CANTAKE       = 0, -- 可领奖励
    NEWUSERREWARD_REWARDSTATE_REWARDED      = 1, -- 已领奖励
    NEWUSERREWARD_REWARDSTATE_UPTOLIMIT     = 2, -- 设备上限
    NEWUSERREWARD_REWARDSTATE_NOTHISREWARD  = 3, -- 没有奖励

    NEWUSERREWARD_CONFIGSTATE_DISABLE       = 0, -- 奖励配置已关
    NEWUSERREWARD_CONFIGSTATE_ENABLE        = 1, -- 奖励配置已开
    NEWUSERREWARD_CONFIGSTATE_NOTHISCONFIG  = 2, -- 没有奖励配置

    NEWUSERREWARD_REWARDRESULT_SUCCESS      = 0, -- 奖励领取成功
    NEWUSERREWARD_REWARDRESULT_DISABLE      = 1, -- 奖励配置关闭
    NEWUSERREWARD_REWARDRESULT_NOTHISCONFIG = 2, -- 没有奖励配置
    NEWUSERREWARD_REWARDRESULT_REWARDED     = 3, -- 奖励已经领取
    NEWUSERREWARD_REWARDRESULT_UPTOLIMIT    = 4, -- 已达领取上限
    NEWUSERREWARD_REWARDRESULT_FAILD        = 5, -- 奖励领取失败

    EVENT_NEWUSERREWARD_DATA_READY          = "EVENT_NEWUSERREWARD_DATA_READY",
    EVENT_NEWUSERREWARD_TAKE_REWARD_OK      = "EVENT_NEWUSERREWARD_TAKE_REWARD_OK"
}
return NewUserRewardDef
