local WeekMonthSuperCardDef = 
{
	GR_WEEK_MONTH_SUPER_CARD_QUERY_CONFIG 	= (400000 + 3401),		-- 获取周月至尊卡配置数据		
    GR_WEEK_MONTH_SUPER_CARD_QUERY_INFO 	= (400000 + 3402),		-- 获取周月至尊卡信息
    GR_WEEK_MONTH_SUPER_CARD_AWARD 			= (400000 + 3403),		-- 领取周月至尊卡奖励
	GR_WEEK_MONTH_SUPER_CARD_PAY_SUCCEED 	= (400000 + 3404),		-- 周月至尊卡购买成功、
	GR_WEEK_MONTH_SUPER_CARD_SAVE_CHANNEL_ID= (400000 + 3405),		-- 保存周月至尊卡渠道号信息
	
	WEEK_MONTH_SUPER_CARD_QUERY_CONFIG_RSP 	= 'WEEK_MONTH_SUPER_CARD_QUERY_CONFIG_RSP',
	WEEK_MONTH_SUPER_CARD_QUERY_INFO_RSP 	= 'WEEK_MONTH_SUPER_CARD_QUERY_INFO_RSP',
	WEEK_MONTH_SUPER_CARD_TAKE_AWARD_RSP 	= 'WEEK_MONTH_SUPER_CARD_TAKE_AWARD_RSP',
	WEEK_MONTH_SUPER_CARD_PAY_PAY_SUCCEED 	= 'WEEK_MONTH_SUPER_CARD_PAY_SUCCEED',
    
    WEEK_MONTH_SUPER_CARD_APPTYPE_AN_TCY 	= 1,
	WEEK_MONTH_SUPER_CARD_APPTYPE_AN_SINGLE = 2,
	WEEK_MONTH_SUPER_CARD_APPTYPE_AN_SET 	= 3,
	WEEK_MONTH_SUPER_CARD_APPTYPE_IOS_TCY 	= 4,
    WEEK_MONTH_SUPER_CARD_APPTYPE_IOS_SINGLE= 5,
	
	CARD_TYPE_WEEK_CARD							= 1,		-- 周卡
	CARD_TYPE_MONTH_CARD						= 2,		-- 月卡
	CARD_TYPE_SUPER_CARD						= 3,		-- 至尊卡

	WEEK_MONTH_SUPER_CARD_NOT_ENABLE			= -1,       -- 周月至尊卡未开启
	WEEK_MONTH_SUPER_CARD_NOT_BUY				= 0,        -- 卡包未购买
	WEEK_MONTH_SUPER_CARD_BUYYED				= 1,        -- 卡包已购买
	WEEK_MONTH_SUPER_CARD_NO_AWARD				= 0,        -- 卡包没有奖励
	WEEK_MONTH_SUPER_CARD_NOT_REWARD			= 1,        -- 卡包奖励未领取
	WEEK_MONTH_SUPER_CARD_REWARDED				= 2,        -- 卡包奖励已领取
	WEEK_MONTH_SUPER_CARD_BUY_OK				= 1,        -- 卡包购买成功
	TAKE_DAILY_AWARD_RESULT_SUCCESS				= 1,		-- 领奖成功
	TAKE_DAILY_AWARD_RESULT_CLOSE				= 2,		-- 活动关闭
	TAKE_DAILY_AWARD_RESULT_NOT_BUY				= 3,	 	-- 未购买
	TAKE_DAILY_AWARD_RESULT_RECEIVED 			= 4,	 	-- 已领取
}

return WeekMonthSuperCardDef