local TimingGameDef = 
{
	GR_TIMING_GAME_MSG_BEGIN = (400000 + 2300),
	GR_TIMING_GAME_QUERY_CONFIG = (400000 + 2301),
	GR_TIMING_GAME_QUERY_INFO = (400000 + 2302),
	GR_TIMING_GAME_QUERY_RECORD = (400000 + 2303),
    GR_TIMING_GAME_PAY_SUCCESS = (400000 + 2304),
    GR_TIMING_GAME_APPLY_MATCH = (400000 + 2305),
    GR_TIMING_GAME_TASK_TAKE_AWARD = (400000 + 2306),
    GR_TIMING_GAME_QUERY_ROBOT_CUR_SCORE = (400000 + 2308),

    GR_TIMING_APPLY_MATCH_FAILED = (400000 + 2350),
    
    --报名状态
    TIMING_GAME_APPLY_SUCCESS = 0,
    TIMING_GAME_NO_OPEN = 1,
	TIMING_GAME_NO_MATCH_DATE = 2,
	TIMING_GAME_MATCH_OVER_TIME = 3,
    TIMING_GAME_SEASON_OVER_TIME = 4,
    TIMING_GAME_APPLY_REGISTERED = 5,
    TIMING_GAME_APPLY_OVER_LIMIT = 6,
    TIMING_GAME_TICKET_NOT_ENOUGH = 7,
	
    TIMINGGAME_APPTYPE_AN_TCY = 1,
	TIMINGGAME_APPTYPE_AN_SINGLE = 2,
	TIMINGGAME_APPTYPE_AN_SET = 3,
	TIMINGGAME_APPTYPE_IOS_TCY = 4,
    TIMINGGAME_APPTYPE_IOS_SINGLE = 5,

    --比赛状态
    TIMING_GAME_CAN_START_MATCH = 0,
    TIMING_GAME_NOT_IN_MATCH_PERIOD = 1,
    TIMING_GAME_NOT_APPLY = 2,
	TIMING_GAME_BOUT_NUM_OVER_LIMIT = 3,
    TIMING_GAME_SCORE_NOT_ENOUGH = 4,

    TIMING_GAME_TICKET_TASK_NUM = 4
}

return TimingGameDef