
local getActivitysBaseUrl=myhttp.getActivitysBaseUrl
local getTime=myhttp.getTime
local countKeyString=myhttp.countKeyString
local getDeviceId=myhttp.getDeviceId

local config={

        -- relief
        queryReliefConfig={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetFAConfig',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='ReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        takeRelief={
            kpi = true,
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/SendSilver',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='ReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        queryReliefUserState={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetPresent',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='ReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },


        -- member relief
        queryMemberReliefConfig={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetFAConfig',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='MemberReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        takeMemberRelief={
            kpi = true,
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/SendSilver',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='MemberReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        queryMemberReliefUserState={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetPresent',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='MemberReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },

        --贵族系统 relief
        queryNobilityPrivilegeReliefConfig={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetFAConfig',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NobilityPrivilegeReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        takeNobilityPrivilegeRelief={
            kpi = true,
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/SendSilver',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NobilityPrivilegeReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        queryNobilityPrivilegeReliefUserState={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetPresent',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NobilityPrivilegeReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },

        -- videoad relief
        queryVideoAdReliefConfig={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetFAConfig',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='VideoAdReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        takeVideoAdRelief={
            kpi = true,
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/SendSilver',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='VideoAdReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        queryVideoAdReliefUserState={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetPresent',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='VideoAdReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },

        -- no safebox relief
        queryNoSafeboxReliefConfig={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetFAConfig',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NoSafeboxReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        takeNoSafeboxRelief={
            kpi = true,
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/SendSilver',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NoSafeboxReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        queryNoSafeboxReliefUserState={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetPresent',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NoSafeboxReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },

        -- NPNoSafebox relief
        queryNPNoSafeboxReliefConfig={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetFAConfig',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NPNoSafeboxReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        takeNPNoSafeboxRelief={
            kpi = true,
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/SendSilver',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NPNoSafeboxReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        queryNPNoSafeboxReliefUserState={
            baseUrl=getActivitysBaseUrl(),
            addition='/FloorReward/GetPresent',
            exchangeMap={
                UserName='szUtf8Username',
                ActId='NPNoSafeboxReliefActId',
                UserId='nUserID',
            },
            privateData={
                SilverLocation=0,
                input_charset='UTF-8',
                Time=getTime,
                Key=countKeyString,
                DeviceId=getDeviceId,
            },
        },
        
}

myhttp.registConfigList(config)
