#pragma once

#define PORT_ONLINESVR			61420
enum SOCKCILENT_INDEX{
	SOCKCILENT_ONLINESVR = 10,
	SOCKCILENT_TRANKGAME,
	SOCKCILENT_MAX
};

#define PRODUCT_NAME		_T(GAME_CLIENT"Chunksvr")

#define APPLICATION_TITLE	 _T(GAME_CLIENT"ChunkSvr")
#define STR_SERVICE_NAME     _T(GAME_CLIENT"ChunkSvr")
#define STR_DISPLAY_NAME     _T("同城游"GAME_APPNAME"数据服务")
#define STR_DISPLAY_NAME_ENU _T("TCY "GAME_CLIENT"ChunkSvr Service") 
