
local MyGameReq = {
    CALL_FRIEND={
        lengthMap = {
            [8] = 32,
            [9] = {maxlen = 4},
            maxlen = 10
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nSendTable',
            'nSendChair',
            'nSendUser',
            'szHardID',
            'nReserved',
            'nCardID'
        },
        formatKey = '<iiiiiiiAiiiii',
        deformatKey = '<iiiiiiiA32iiiii',
        maxsize = 80
    },
    
    SHOW_CARDS={
        lengthMap = {
            [9] = 32,
            [10] = {maxlen = 4},
            maxlen = 10
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'bShow',
            'nSendTable',
            'nSendChair',
            'nSendUser',
            'szHardID',
            'nReserved'
        },
        formatKey = '<iiiiiiiiAiiii',
        deformatKey = '<iiiiiiiiA32iiii',
        maxsize = 80
    },

    --[[GAME_START_INFO={
        lengthMap = {
            [19] = {maxlen = 5},
            [20] = {maxlen = 38},
            maxlen = 20
        },
        nameMap = {
            'nBoutCount',
            'nBaseDeposit',
            'nBaseScore',
            'nBanker',
            'nCurrentChair',
            'nFirstCatch',
            'nFirstThrow',
            'nCallWait',
            'nShowWait',
            'nThrowWait',
            'nMaxAutoThrow',
            'nEntrustWait',
            'bNeedDeposit',
            'bForbidDesert',
            'nThrowWaitEx',
            'nTotalOpe',
            'bMemberScoreDoubleOpen',
            'bMemberScoreReduceOpen',
            'nCardsCount',
            'nChairCards'
        },
        formatKey = '<iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 244
    },--]] 

    GAME_START_INFO={
		lengthMap = {
			[1] = {maxlen = 32},
			[14] = {maxlen = 3},
			[15] = {maxlen = 4},
			[16] = {maxlen = 4},
			[22] = {maxlen = 2},
			[27] = {maxlen = 2},
			[32] = {maxlen = 2},
			[37] = {maxlen = 2},
			[38] = {maxlen = 4},
			[41] = {maxlen = 33},
			[42] = {maxlen = 33},
			[43] = {maxlen = 4},
			[44] = {maxlen = 4},
			[45] = {maxlen = 4},
			[50] = {maxlen = 4},
			maxlen = 50
		},
		nameMap = {
			'szSerialNO',
			'nBoutCount',
			'nBaseDeposit',
			'nBaseScore',
			'bNeedDeposit',
			'bForbidDesert',
			'nBanker',
			'nCurrentChair',
			'dwStatus',
			'nThrowWait',
			'nAutoGiveUp',
			'nOffline',
			'nInHandCount',
			'nThrowWaitEx',
			'nRank',
			'nRound',
			'nCurrentRank',
			'bnTribute',
			'winner',
			'nCardID',
			'bnFight',
			'nFightID',
			'bnTribute1',
			'winner1',
			'nCardID1',
			'bnFight1',
			'nFightID1',
			'bnTribute2',
			'winner2',
			'nCardID2',
			'bnFight2',
			'nFightID2',
			'bnTribute3',
			'winner3',
			'nCardID3',
			'bnFight3',
			'nFightID3',
			'nPlace',
			'bnShowRank',
			'bnResetGame',
			'nHandID',
			'nFriendID',
			'nFaceID',
			'nLastScoreDiffs',
			'nTotalScoreDiffs',
			'bnCardMasterChairUse',
			'nObjectGains',
			'nFanPaiCardID',
			'nRanker',
			'nReserved'
		},
		formatKey = '<cccccccccccccccccccccccccccccccciiilliiLiiiiiiiiiiiiiiiiliiliiliiliiliiliiliiliiiiiilliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiliiiiiii',
		deformatKey = '<cccccccccccccccccccccccccccccccciiilliiLiiiiiiiiiiiiiiiiliiliiliiliiliiliiliiliiiiiilliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiliiiiiii',
		maxsize = 592
	},
	
	GAME_TABLE_INFO={
		lengthMap = {
			[1] = {maxlen = 32},
			[14] = {maxlen = 3},
			[15] = {maxlen = 4},
			[16] = {maxlen = 4},
			[22] = {maxlen = 2},
			[27] = {maxlen = 2},
			[32] = {maxlen = 2},
			[37] = {maxlen = 2},
			[38] = {maxlen = 4},
			[41] = {maxlen = 33},
			[42] = {maxlen = 33},
			[43] = {maxlen = 4},
			[44] = {maxlen = 4},
			[45] = {maxlen = 4},
			[50] = {maxlen = 4},
			[56] = {maxlen = 64},
			[59] = {maxlen = 8},
			[924] = {maxlen = 4},
			[925] = {maxlen = 30,maxwidth = 8,complexType = 'matrix2'},
			[926] = {maxlen = 8},
			[927] = {maxlen = 4},
			[933] = {maxlen = 108},
			[934] = {maxlen = 4},
			[937] = {maxlen = 4},
			[943] = {maxlen = 108},
			[944] = {maxlen = 4},
			[947] = {maxlen = 4},
			[953] = {maxlen = 108},
			[954] = {maxlen = 4},
			[957] = {maxlen = 4},
			[963] = {maxlen = 108},
			[964] = {maxlen = 4},
			[967] = {maxlen = 4},
			[968] = {maxlen = 4},
			maxlen = 968
		},
		nameMap = {
			'szSerialNO',
			'nBoutCount',
			'nBaseDeposit',
			'nBaseScore',
			'bNeedDeposit',
			'bForbidDesert',
			'nBanker',
			'nCurrentChair',
			'dwStatus',
			'nThrowWait',
			'nAutoGiveUp',
			'nOffline',
			'nInHandCount',
			'nThrowWaitEx',
			'nRank',
			'nRound',
			'nCurrentRank',
			'bnTribute',
			'winner',
			'nCardID',
			'bnFight',
			'nFightID',
			'bnTribute1',
			'winner1',
			'nCardID1',
			'bnFight1',
			'nFightID1',
			'bnTribute2',
			'winner2',
			'nCardID2',
			'bnFight2',
			'nFightID2',
			'bnTribute3',
			'winner3',
			'nCardID3',
			'bnFight3',
			'nFightID3',
			'nPlace',
			'bnShowRank',
			'bnResetGame',
			'nHandID',
			'nFriendID',
			'nFaceID',
			'nLastScoreDiffs',
			'nTotalScoreDiffs',
			'bnCardMasterChairUse',
			'nObjectGains',
			'nFanPaiCardID',
			'nRanker',
			'nReserved',
			'nWaitChair',
			'dwCardType',
			'dwComPareType',
			'nMainValue',
			'nCardCount',
			'nCardIDs',
			'nCurrentCatch',
			'nCurrentRank1',
			'dwUserStatus',
			'nCardID4',
			'nCardIndex',
			'nShape',
			'nValue',
			'nCardStatus',
			'nChairNO',
			'nPositionIndex',
			'nUniteCount',
			'nCardID5',
			'nCardIndex1',
			'nShape1',
			'nValue1',
			'nCardStatus1',
			'nChairNO1',
			'nPositionIndex1',
			'nUniteCount1',
			'nCardID6',
			'nCardIndex2',
			'nShape2',
			'nValue2',
			'nCardStatus2',
			'nChairNO2',
			'nPositionIndex2',
			'nUniteCount2',
			'nCardID7',
			'nCardIndex3',
			'nShape3',
			'nValue3',
			'nCardStatus3',
			'nChairNO3',
			'nPositionIndex3',
			'nUniteCount3',
			'nCardID8',
			'nCardIndex4',
			'nShape4',
			'nValue4',
			'nCardStatus4',
			'nChairNO4',
			'nPositionIndex4',
			'nUniteCount4',
			'nCardID9',
			'nCardIndex5',
			'nShape5',
			'nValue5',
			'nCardStatus5',
			'nChairNO5',
			'nPositionIndex5',
			'nUniteCount5',
			'nCardID10',
			'nCardIndex6',
			'nShape6',
			'nValue6',
			'nCardStatus6',
			'nChairNO6',
			'nPositionIndex6',
			'nUniteCount6',
			'nCardID11',
			'nCardIndex7',
			'nShape7',
			'nValue7',
			'nCardStatus7',
			'nChairNO7',
			'nPositionIndex7',
			'nUniteCount7',
			'nCardID12',
			'nCardIndex8',
			'nShape8',
			'nValue8',
			'nCardStatus8',
			'nChairNO8',
			'nPositionIndex8',
			'nUniteCount8',
			'nCardID13',
			'nCardIndex9',
			'nShape9',
			'nValue9',
			'nCardStatus9',
			'nChairNO9',
			'nPositionIndex9',
			'nUniteCount9',
			'nCardID14',
			'nCardIndex10',
			'nShape10',
			'nValue10',
			'nCardStatus10',
			'nChairNO10',
			'nPositionIndex10',
			'nUniteCount10',
			'nCardID15',
			'nCardIndex11',
			'nShape11',
			'nValue11',
			'nCardStatus11',
			'nChairNO11',
			'nPositionIndex11',
			'nUniteCount11',
			'nCardID16',
			'nCardIndex12',
			'nShape12',
			'nValue12',
			'nCardStatus12',
			'nChairNO12',
			'nPositionIndex12',
			'nUniteCount12',
			'nCardID17',
			'nCardIndex13',
			'nShape13',
			'nValue13',
			'nCardStatus13',
			'nChairNO13',
			'nPositionIndex13',
			'nUniteCount13',
			'nCardID18',
			'nCardIndex14',
			'nShape14',
			'nValue14',
			'nCardStatus14',
			'nChairNO14',
			'nPositionIndex14',
			'nUniteCount14',
			'nCardID19',
			'nCardIndex15',
			'nShape15',
			'nValue15',
			'nCardStatus15',
			'nChairNO15',
			'nPositionIndex15',
			'nUniteCount15',
			'nCardID20',
			'nCardIndex16',
			'nShape16',
			'nValue16',
			'nCardStatus16',
			'nChairNO16',
			'nPositionIndex16',
			'nUniteCount16',
			'nCardID21',
			'nCardIndex17',
			'nShape17',
			'nValue17',
			'nCardStatus17',
			'nChairNO17',
			'nPositionIndex17',
			'nUniteCount17',
			'nCardID22',
			'nCardIndex18',
			'nShape18',
			'nValue18',
			'nCardStatus18',
			'nChairNO18',
			'nPositionIndex18',
			'nUniteCount18',
			'nCardID23',
			'nCardIndex19',
			'nShape19',
			'nValue19',
			'nCardStatus19',
			'nChairNO19',
			'nPositionIndex19',
			'nUniteCount19',
			'nCardID24',
			'nCardIndex20',
			'nShape20',
			'nValue20',
			'nCardStatus20',
			'nChairNO20',
			'nPositionIndex20',
			'nUniteCount20',
			'nCardID25',
			'nCardIndex21',
			'nShape21',
			'nValue21',
			'nCardStatus21',
			'nChairNO21',
			'nPositionIndex21',
			'nUniteCount21',
			'nCardID26',
			'nCardIndex22',
			'nShape22',
			'nValue22',
			'nCardStatus22',
			'nChairNO22',
			'nPositionIndex22',
			'nUniteCount22',
			'nCardID27',
			'nCardIndex23',
			'nShape23',
			'nValue23',
			'nCardStatus23',
			'nChairNO23',
			'nPositionIndex23',
			'nUniteCount23',
			'nCardID28',
			'nCardIndex24',
			'nShape24',
			'nValue24',
			'nCardStatus24',
			'nChairNO24',
			'nPositionIndex24',
			'nUniteCount24',
			'nCardID29',
			'nCardIndex25',
			'nShape25',
			'nValue25',
			'nCardStatus25',
			'nChairNO25',
			'nPositionIndex25',
			'nUniteCount25',
			'nCardID30',
			'nCardIndex26',
			'nShape26',
			'nValue26',
			'nCardStatus26',
			'nChairNO26',
			'nPositionIndex26',
			'nUniteCount26',
			'nCardID31',
			'nCardIndex27',
			'nShape27',
			'nValue27',
			'nCardStatus27',
			'nChairNO27',
			'nPositionIndex27',
			'nUniteCount27',
			'nCardID32',
			'nCardIndex28',
			'nShape28',
			'nValue28',
			'nCardStatus28',
			'nChairNO28',
			'nPositionIndex28',
			'nUniteCount28',
			'nCardID33',
			'nCardIndex29',
			'nShape29',
			'nValue29',
			'nCardStatus29',
			'nChairNO29',
			'nPositionIndex29',
			'nUniteCount29',
			'nCardID34',
			'nCardIndex30',
			'nShape30',
			'nValue30',
			'nCardStatus30',
			'nChairNO30',
			'nPositionIndex30',
			'nUniteCount30',
			'nCardID35',
			'nCardIndex31',
			'nShape31',
			'nValue31',
			'nCardStatus31',
			'nChairNO31',
			'nPositionIndex31',
			'nUniteCount31',
			'nCardID36',
			'nCardIndex32',
			'nShape32',
			'nValue32',
			'nCardStatus32',
			'nChairNO32',
			'nPositionIndex32',
			'nUniteCount32',
			'nCardID37',
			'nCardIndex33',
			'nShape33',
			'nValue33',
			'nCardStatus33',
			'nChairNO33',
			'nPositionIndex33',
			'nUniteCount33',
			'nCardID38',
			'nCardIndex34',
			'nShape34',
			'nValue34',
			'nCardStatus34',
			'nChairNO34',
			'nPositionIndex34',
			'nUniteCount34',
			'nCardID39',
			'nCardIndex35',
			'nShape35',
			'nValue35',
			'nCardStatus35',
			'nChairNO35',
			'nPositionIndex35',
			'nUniteCount35',
			'nCardID40',
			'nCardIndex36',
			'nShape36',
			'nValue36',
			'nCardStatus36',
			'nChairNO36',
			'nPositionIndex36',
			'nUniteCount36',
			'nCardID41',
			'nCardIndex37',
			'nShape37',
			'nValue37',
			'nCardStatus37',
			'nChairNO37',
			'nPositionIndex37',
			'nUniteCount37',
			'nCardID42',
			'nCardIndex38',
			'nShape38',
			'nValue38',
			'nCardStatus38',
			'nChairNO38',
			'nPositionIndex38',
			'nUniteCount38',
			'nCardID43',
			'nCardIndex39',
			'nShape39',
			'nValue39',
			'nCardStatus39',
			'nChairNO39',
			'nPositionIndex39',
			'nUniteCount39',
			'nCardID44',
			'nCardIndex40',
			'nShape40',
			'nValue40',
			'nCardStatus40',
			'nChairNO40',
			'nPositionIndex40',
			'nUniteCount40',
			'nCardID45',
			'nCardIndex41',
			'nShape41',
			'nValue41',
			'nCardStatus41',
			'nChairNO41',
			'nPositionIndex41',
			'nUniteCount41',
			'nCardID46',
			'nCardIndex42',
			'nShape42',
			'nValue42',
			'nCardStatus42',
			'nChairNO42',
			'nPositionIndex42',
			'nUniteCount42',
			'nCardID47',
			'nCardIndex43',
			'nShape43',
			'nValue43',
			'nCardStatus43',
			'nChairNO43',
			'nPositionIndex43',
			'nUniteCount43',
			'nCardID48',
			'nCardIndex44',
			'nShape44',
			'nValue44',
			'nCardStatus44',
			'nChairNO44',
			'nPositionIndex44',
			'nUniteCount44',
			'nCardID49',
			'nCardIndex45',
			'nShape45',
			'nValue45',
			'nCardStatus45',
			'nChairNO45',
			'nPositionIndex45',
			'nUniteCount45',
			'nCardID50',
			'nCardIndex46',
			'nShape46',
			'nValue46',
			'nCardStatus46',
			'nChairNO46',
			'nPositionIndex46',
			'nUniteCount46',
			'nCardID51',
			'nCardIndex47',
			'nShape47',
			'nValue47',
			'nCardStatus47',
			'nChairNO47',
			'nPositionIndex47',
			'nUniteCount47',
			'nCardID52',
			'nCardIndex48',
			'nShape48',
			'nValue48',
			'nCardStatus48',
			'nChairNO48',
			'nPositionIndex48',
			'nUniteCount48',
			'nCardID53',
			'nCardIndex49',
			'nShape49',
			'nValue49',
			'nCardStatus49',
			'nChairNO49',
			'nPositionIndex49',
			'nUniteCount49',
			'nCardID54',
			'nCardIndex50',
			'nShape50',
			'nValue50',
			'nCardStatus50',
			'nChairNO50',
			'nPositionIndex50',
			'nUniteCount50',
			'nCardID55',
			'nCardIndex51',
			'nShape51',
			'nValue51',
			'nCardStatus51',
			'nChairNO51',
			'nPositionIndex51',
			'nUniteCount51',
			'nCardID56',
			'nCardIndex52',
			'nShape52',
			'nValue52',
			'nCardStatus52',
			'nChairNO52',
			'nPositionIndex52',
			'nUniteCount52',
			'nCardID57',
			'nCardIndex53',
			'nShape53',
			'nValue53',
			'nCardStatus53',
			'nChairNO53',
			'nPositionIndex53',
			'nUniteCount53',
			'nCardID58',
			'nCardIndex54',
			'nShape54',
			'nValue54',
			'nCardStatus54',
			'nChairNO54',
			'nPositionIndex54',
			'nUniteCount54',
			'nCardID59',
			'nCardIndex55',
			'nShape55',
			'nValue55',
			'nCardStatus55',
			'nChairNO55',
			'nPositionIndex55',
			'nUniteCount55',
			'nCardID60',
			'nCardIndex56',
			'nShape56',
			'nValue56',
			'nCardStatus56',
			'nChairNO56',
			'nPositionIndex56',
			'nUniteCount56',
			'nCardID61',
			'nCardIndex57',
			'nShape57',
			'nValue57',
			'nCardStatus57',
			'nChairNO57',
			'nPositionIndex57',
			'nUniteCount57',
			'nCardID62',
			'nCardIndex58',
			'nShape58',
			'nValue58',
			'nCardStatus58',
			'nChairNO58',
			'nPositionIndex58',
			'nUniteCount58',
			'nCardID63',
			'nCardIndex59',
			'nShape59',
			'nValue59',
			'nCardStatus59',
			'nChairNO59',
			'nPositionIndex59',
			'nUniteCount59',
			'nCardID64',
			'nCardIndex60',
			'nShape60',
			'nValue60',
			'nCardStatus60',
			'nChairNO60',
			'nPositionIndex60',
			'nUniteCount60',
			'nCardID65',
			'nCardIndex61',
			'nShape61',
			'nValue61',
			'nCardStatus61',
			'nChairNO61',
			'nPositionIndex61',
			'nUniteCount61',
			'nCardID66',
			'nCardIndex62',
			'nShape62',
			'nValue62',
			'nCardStatus62',
			'nChairNO62',
			'nPositionIndex62',
			'nUniteCount62',
			'nCardID67',
			'nCardIndex63',
			'nShape63',
			'nValue63',
			'nCardStatus63',
			'nChairNO63',
			'nPositionIndex63',
			'nUniteCount63',
			'nCardID68',
			'nCardIndex64',
			'nShape64',
			'nValue64',
			'nCardStatus64',
			'nChairNO64',
			'nPositionIndex64',
			'nUniteCount64',
			'nCardID69',
			'nCardIndex65',
			'nShape65',
			'nValue65',
			'nCardStatus65',
			'nChairNO65',
			'nPositionIndex65',
			'nUniteCount65',
			'nCardID70',
			'nCardIndex66',
			'nShape66',
			'nValue66',
			'nCardStatus66',
			'nChairNO66',
			'nPositionIndex66',
			'nUniteCount66',
			'nCardID71',
			'nCardIndex67',
			'nShape67',
			'nValue67',
			'nCardStatus67',
			'nChairNO67',
			'nPositionIndex67',
			'nUniteCount67',
			'nCardID72',
			'nCardIndex68',
			'nShape68',
			'nValue68',
			'nCardStatus68',
			'nChairNO68',
			'nPositionIndex68',
			'nUniteCount68',
			'nCardID73',
			'nCardIndex69',
			'nShape69',
			'nValue69',
			'nCardStatus69',
			'nChairNO69',
			'nPositionIndex69',
			'nUniteCount69',
			'nCardID74',
			'nCardIndex70',
			'nShape70',
			'nValue70',
			'nCardStatus70',
			'nChairNO70',
			'nPositionIndex70',
			'nUniteCount70',
			'nCardID75',
			'nCardIndex71',
			'nShape71',
			'nValue71',
			'nCardStatus71',
			'nChairNO71',
			'nPositionIndex71',
			'nUniteCount71',
			'nCardID76',
			'nCardIndex72',
			'nShape72',
			'nValue72',
			'nCardStatus72',
			'nChairNO72',
			'nPositionIndex72',
			'nUniteCount72',
			'nCardID77',
			'nCardIndex73',
			'nShape73',
			'nValue73',
			'nCardStatus73',
			'nChairNO73',
			'nPositionIndex73',
			'nUniteCount73',
			'nCardID78',
			'nCardIndex74',
			'nShape74',
			'nValue74',
			'nCardStatus74',
			'nChairNO74',
			'nPositionIndex74',
			'nUniteCount74',
			'nCardID79',
			'nCardIndex75',
			'nShape75',
			'nValue75',
			'nCardStatus75',
			'nChairNO75',
			'nPositionIndex75',
			'nUniteCount75',
			'nCardID80',
			'nCardIndex76',
			'nShape76',
			'nValue76',
			'nCardStatus76',
			'nChairNO76',
			'nPositionIndex76',
			'nUniteCount76',
			'nCardID81',
			'nCardIndex77',
			'nShape77',
			'nValue77',
			'nCardStatus77',
			'nChairNO77',
			'nPositionIndex77',
			'nUniteCount77',
			'nCardID82',
			'nCardIndex78',
			'nShape78',
			'nValue78',
			'nCardStatus78',
			'nChairNO78',
			'nPositionIndex78',
			'nUniteCount78',
			'nCardID83',
			'nCardIndex79',
			'nShape79',
			'nValue79',
			'nCardStatus79',
			'nChairNO79',
			'nPositionIndex79',
			'nUniteCount79',
			'nCardID84',
			'nCardIndex80',
			'nShape80',
			'nValue80',
			'nCardStatus80',
			'nChairNO80',
			'nPositionIndex80',
			'nUniteCount80',
			'nCardID85',
			'nCardIndex81',
			'nShape81',
			'nValue81',
			'nCardStatus81',
			'nChairNO81',
			'nPositionIndex81',
			'nUniteCount81',
			'nCardID86',
			'nCardIndex82',
			'nShape82',
			'nValue82',
			'nCardStatus82',
			'nChairNO82',
			'nPositionIndex82',
			'nUniteCount82',
			'nCardID87',
			'nCardIndex83',
			'nShape83',
			'nValue83',
			'nCardStatus83',
			'nChairNO83',
			'nPositionIndex83',
			'nUniteCount83',
			'nCardID88',
			'nCardIndex84',
			'nShape84',
			'nValue84',
			'nCardStatus84',
			'nChairNO84',
			'nPositionIndex84',
			'nUniteCount84',
			'nCardID89',
			'nCardIndex85',
			'nShape85',
			'nValue85',
			'nCardStatus85',
			'nChairNO85',
			'nPositionIndex85',
			'nUniteCount85',
			'nCardID90',
			'nCardIndex86',
			'nShape86',
			'nValue86',
			'nCardStatus86',
			'nChairNO86',
			'nPositionIndex86',
			'nUniteCount86',
			'nCardID91',
			'nCardIndex87',
			'nShape87',
			'nValue87',
			'nCardStatus87',
			'nChairNO87',
			'nPositionIndex87',
			'nUniteCount87',
			'nCardID92',
			'nCardIndex88',
			'nShape88',
			'nValue88',
			'nCardStatus88',
			'nChairNO88',
			'nPositionIndex88',
			'nUniteCount88',
			'nCardID93',
			'nCardIndex89',
			'nShape89',
			'nValue89',
			'nCardStatus89',
			'nChairNO89',
			'nPositionIndex89',
			'nUniteCount89',
			'nCardID94',
			'nCardIndex90',
			'nShape90',
			'nValue90',
			'nCardStatus90',
			'nChairNO90',
			'nPositionIndex90',
			'nUniteCount90',
			'nCardID95',
			'nCardIndex91',
			'nShape91',
			'nValue91',
			'nCardStatus91',
			'nChairNO91',
			'nPositionIndex91',
			'nUniteCount91',
			'nCardID96',
			'nCardIndex92',
			'nShape92',
			'nValue92',
			'nCardStatus92',
			'nChairNO92',
			'nPositionIndex92',
			'nUniteCount92',
			'nCardID97',
			'nCardIndex93',
			'nShape93',
			'nValue93',
			'nCardStatus93',
			'nChairNO93',
			'nPositionIndex93',
			'nUniteCount93',
			'nCardID98',
			'nCardIndex94',
			'nShape94',
			'nValue94',
			'nCardStatus94',
			'nChairNO94',
			'nPositionIndex94',
			'nUniteCount94',
			'nCardID99',
			'nCardIndex95',
			'nShape95',
			'nValue95',
			'nCardStatus95',
			'nChairNO95',
			'nPositionIndex95',
			'nUniteCount95',
			'nCardID100',
			'nCardIndex96',
			'nShape96',
			'nValue96',
			'nCardStatus96',
			'nChairNO96',
			'nPositionIndex96',
			'nUniteCount96',
			'nCardID101',
			'nCardIndex97',
			'nShape97',
			'nValue97',
			'nCardStatus97',
			'nChairNO97',
			'nPositionIndex97',
			'nUniteCount97',
			'nCardID102',
			'nCardIndex98',
			'nShape98',
			'nValue98',
			'nCardStatus98',
			'nChairNO98',
			'nPositionIndex98',
			'nUniteCount98',
			'nCardID103',
			'nCardIndex99',
			'nShape99',
			'nValue99',
			'nCardStatus99',
			'nChairNO99',
			'nPositionIndex99',
			'nUniteCount99',
			'nCardID104',
			'nCardIndex100',
			'nShape100',
			'nValue100',
			'nCardStatus100',
			'nChairNO100',
			'nPositionIndex100',
			'nUniteCount100',
			'nCardID105',
			'nCardIndex101',
			'nShape101',
			'nValue101',
			'nCardStatus101',
			'nChairNO101',
			'nPositionIndex101',
			'nUniteCount101',
			'nCardID106',
			'nCardIndex102',
			'nShape102',
			'nValue102',
			'nCardStatus102',
			'nChairNO102',
			'nPositionIndex102',
			'nUniteCount102',
			'nCardID107',
			'nCardIndex103',
			'nShape103',
			'nValue103',
			'nCardStatus103',
			'nChairNO103',
			'nPositionIndex103',
			'nUniteCount103',
			'nCardID108',
			'nCardIndex104',
			'nShape104',
			'nValue104',
			'nCardStatus104',
			'nChairNO104',
			'nPositionIndex104',
			'nUniteCount104',
			'nCardID109',
			'nCardIndex105',
			'nShape105',
			'nValue105',
			'nCardStatus105',
			'nChairNO105',
			'nPositionIndex105',
			'nUniteCount105',
			'nCardID110',
			'nCardIndex106',
			'nShape106',
			'nValue106',
			'nCardStatus106',
			'nChairNO106',
			'nPositionIndex106',
			'nUniteCount106',
			'nCardID111',
			'nCardIndex107',
			'nShape107',
			'nValue107',
			'nCardStatus107',
			'nChairNO107',
			'nPositionIndex107',
			'nUniteCount107',
			'bnChairWin',
			'nResultDiff',
			'nTotalResult',
			'nReserved1',
			'nWaitTime',
			'nThrowTime',
			'nTotalThrowCost',
			'nInHandCount1',
			'nAutoThrowCount',
			'nThrowID',
			'nBombCount',
			'nThrowCount',
			'nAskExitCount',
			'nReserved2',
			'nWaitTime1',
			'nThrowTime1',
			'nTotalThrowCost1',
			'nInHandCount2',
			'nAutoThrowCount1',
			'nThrowID1',
			'nBombCount1',
			'nThrowCount1',
			'nAskExitCount1',
			'nReserved3',
			'nWaitTime2',
			'nThrowTime2',
			'nTotalThrowCost2',
			'nInHandCount3',
			'nAutoThrowCount2',
			'nThrowID2',
			'nBombCount2',
			'nThrowCount2',
			'nAskExitCount2',
			'nReserved4',
			'nWaitTime3',
			'nThrowTime3',
			'nTotalThrowCost3',
			'nInHandCount4',
			'nAutoThrowCount3',
			'nThrowID3',
			'nBombCount3',
			'nThrowCount3',
			'nAskExitCount3',
			'nReserved5',
			'nReserved6'
		},
		formatKey = '<cccccccccccccccccccccccccccccccciiilliiLiiiiiiiiiiiiiiiiliiliiliiliiliiliiliiliiiiiilliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiliiiiiiiiLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLLLLLLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiilllliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
		deformatKey = '<cccccccccccccccccccccccccccccccciiilliiLiiiiiiiiiiiiiiiiliiliiliiliiliiliiliiliiiiiilliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiliiiiiiiiLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLLLLLLLLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiilllliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
		maxsize = 7372
	},
    --[[GAME_TABLE_INFO={
        lengthMap = {
            [20] = {maxlen = 5},
            [21] = {maxlen = 38},
            [23] = {maxlen = 5},
            [27] = {maxlen = 38},
            [28] = {maxlen = 4},
            [30] = {maxlen = 5},
            [31] = {maxlen = 5},
            [34] = {maxlen = 38,maxwidth = 5,complexType = 'matrix2'},
            [35] = {maxlen = 5},
            [36] = {maxlen = 5},
            [37] = {maxlen = 100,maxwidth = 5,complexType = 'matrix2'},
            [38] = {maxlen = 5},
            maxlen = 38
        },
        nameMap = {
            'nBoutCount',
            'nBaseDeposit',
            'nBaseScore',
            'nBanker',
            'nCurrentChair',
            'nFirstCatch',
            'nFirstThrow',
            'nCallWait',
            'nShowWait',
            'nThrowWait',
            'nMaxAutoThrow',
            'nEntrustWait',
            'bNeedDeposit',
            'bForbidDesert',
            'nThrowWaitEx',
            'nTotalOpe',
            'bMemberScoreDoubleOpen',
            'bMemberScoreReduceOpen',
            'bSignInOpen',
            'nCardsCount',
            'nChairCards',
            'dwStatus',
            'bFinishShow',
            'nThrowCount',
            'nWaitingChair',
            'dwWaitingType',
            'nWaitingCards',
            'nReserved',
            'nWaitingGains',
            'nGains',
            'nBonus',
            'nFriendCard',
            'nFriendChair',
            'nShowCards',
            'nLast',
            'nTotal',
            'nScoreex',
            'nTotalScoreex'
        },
        formatKey = '<iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLiiiiiiiLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        deformatKey = '<iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiLiiiiiiiLiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
        maxsize = 3324
    },--]]

    GAME_WIN_RESULT={
		lengthMap = {
			[6] = {maxlen = 8},
			[8] = {maxlen = 8},
			[11] = {maxlen = 8},
			[12] = {maxlen = 8},
			[13] = {maxlen = 8},
			[14] = {maxlen = 8},
			[15] = {maxlen = 8},
			[16] = {maxlen = 8},
			[17] = {maxlen = 16,maxwidth = 8,complexType = 'matrix2'},
			[20] = {maxlen = 2},
			[23] = {maxlen = 4},
			[24] = {maxlen = 4},
			[25] = {maxlen = 4},
			[26] = {maxlen = 4},
			[27] = {maxlen = 4},
			[28] = {maxlen = 4},
			[29] = {maxlen = 33,maxwidth = 4,complexType = 'matrix2'},
			[30] = {maxlen = 4},
			[32] = {maxlen = 4},
			[33] = {maxlen = 4},
			[34] = {maxlen = 4},
			maxlen = 34
		},
		nameMap = {
			'dwWinFlags',
			'dwNextFlags',
			'nTotalChairs',
			'nBoutCount',
			'nBanker',
			'nPartnerGroup',
			'bBankWin',
			'nWinPoints',
			'nBaseScore',
			'nBaseDeposit',
			'nOldScores',
			'nOldDeposits',
			'nScoreDiffs',
			'nDepositDiffs',
			'nWinFees',
			'nLevelIDs',
			'szLevelNames',
			'nNextBaseDeposit',
			'nIdlePlayerFlag',
			'nReserved',
			'bnResetGame',
			'bEnableLeave',
			'nPlace',
			'nUpRank',
			'nNextRank',
			'nBombCount',
			'nBombBoun',
			'nResultBoun',
			'nCardID',
			'nCardCount',
			'nNextBaseScore',
			'nReserved1',
            'nLevelExpUp',
            'nExchangeVouNum'
		},
		formatKey = '<LLiiiiiiiiiiiliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiicccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccciiiilliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
		deformatKey = '<LLiiiiiiiiiiiliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiicccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccciiiilliiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii',
		maxsize = 1132
	},

    TRIBUTE={
		lengthMap = {
			[5] = {maxlen = 2},
			maxlen = 5
		},
		nameMap = {
			'bnTribute',
			'winner',
			'nCardID',
			'bnFight',
			'nFightID'
		},
		formatKey = '<liilii',
		deformatKey = '<liilii',
		maxsize = 24
	},
	
	TRIBUTECARD={
		lengthMap = {
			--,
			maxlen = 2
		},
		nameMap = {
			'chairno',
			'nCardID'
		},
		formatKey = '<ii',
		deformatKey = '<ii',
		maxsize = 8
	},

    RETURNCARD={
		lengthMap = {
			--,
			maxlen = 4
		},
		nameMap = {
			'chairno',
			'nCardID',
            'nTributeChair',
            'nThrowChair'
		},
		formatKey = '<iiii',
		deformatKey = '<iiii',
		maxsize = 16
	},
	
	TRIBUTECARDOVER={
		lengthMap = {
			[5] = {maxlen = 2},
			[10] = {maxlen = 2},
			[15] = {maxlen = 2},
			[20] = {maxlen = 2},
			maxlen = 21
		},
		nameMap = {
			'bnTribute',
			'winner',
			'nCardID',
			'bnFight',
			'nFightID',
			'bnTribute1',
			'winner1',
			'nCardID1',
			'bnFight1',
			'nFightID1',
			'bnTribute2',
			'winner2',
			'nCardID2',
			'bnFight2',
			'nFightID2',
			'bnTribute3',
			'winner3',
			'nCardID3',
			'bnFight3',
			'nFightID3',
			'nBanker'
		},
		formatKey = '<liiliiliiliiliiliiliiliii',
		deformatKey = '<liiliiliiliiliiliiliiliii',
		maxsize = 100
	},

    GAME_MSG_TRIBUTE_CARD={
        lengthMap = {
            --,
            maxlen = 7
        },
        nameMap = {
            'nRoomID',
            'nUserID',
            'nMsgID',
            'bNeedEcho',
            'nDatalen',
            'chairno',
            'nCardID'
        },
        formatKey = '<iiiiiii',
        deformatKey = '<iiiiiii',
        maxsize = 28
    },

    GAME_MSG_RETURN_CARD={
        lengthMap = {
            --,
            maxlen = 9
        },
        nameMap = {
            'nRoomID',
            'nUserID',
            'nMsgID',
            'bNeedEcho',
            'nDatalen',
            'chairno',
            'nCardID',
            'nTributeChair',
            'nThrowChair'
        },
        formatKey = '<iiiiiiiii',
        deformatKey = '<iiiiiiiii',
        maxsize = 36
    },

    GAME_MSG_TRIBUTE_CARD_OVER={
        lengthMap = {
            [10] = {maxlen = 2},
			[15] = {maxlen = 2},
			[20] = {maxlen = 2},
			[25] = {maxlen = 2},
            maxlen = 26
        },
        nameMap = {
            'nRoomID',
            'nUserID',
            'nMsgID',
            'bNeedEcho',
            'nDatalen',
            'bnTribute',
			'winner',
			'nCardID',
			'bnFight',
			'nFightID',
			'bnTribute1',
			'winner1',
			'nCardID1',
			'bnFight1',
			'nFightID1',
			'bnTribute2',
			'winner2',
			'nCardID2',
			'bnFight2',
			'nFightID2',
			'bnTribute3',
			'winner3',
			'nCardID3',
			'bnFight3',
			'nFightID3',
			'nBanker'
        },
        formatKey = '<iiiiiliiliiliiliiliiliiliiliii',
        deformatKey = '<iiiiiliiliiliiliiliiliiliiliii',
        maxsize = 120
    },

    GAME_MSG={
        lengthMap = {
            --,
            maxlen = 5
        },
        nameMap = {
            'nRoomID',
            'nUserID',
            'nMsgID',
            'bNeedEcho',
            'nDatalen'
        },
        formatKey = '<iiiii',
        deformatKey = '<iiiii',
        maxsize = 20
    },

    SYSTEM_MSG={
        lengthMap = {
            --,
            maxlen = 5
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'dwFlag'
        },
        formatKey = '<iiiiL',
        deformatKey = '<iiiiL',
        maxsize = 20
    },
    
    TASKDATA_MSG={
        lengthMap = {
            --,
            maxlen = 14
        },
        nameMap = {
            'nUserID',
            'nTask1Count',
            'task1Finished',
            'nTask2Count',
            'task2Finished',
            'nTask3Count',
            'task3Finished',
            'nTask4Count',
            'task4Finished',
            'nTask5Count',
            'task5Finished',
            'nTask6Count',
            'task6Finished',
            'nTaskCount'
        },
        formatKey = '<iiiiiiiiiiiiii',
        deformatKey = '<iiiiiiiiiiiiii',
        maxsize = 56
    },
    KPIMBHardInfo={
		lengthMap = {
													-- ImeiId	: maxsize = 32	=	1 * 32 * 1,
			[1] = 32,
													-- WifiId	: maxsize = 32	=	1 * 32 * 1,
			[2] = 32,
													-- ImsiId	: maxsize = 32	=	1 * 32 * 1,
			[3] = 32,
													-- SimSerialNo	: maxsize = 32	=	1 * 32 * 1,
			[4] = 32,
													-- SystemId	: maxsize = 32	=	1 * 32 * 1,
			[5] = 32,
													-- nReserved	: maxsize = 128	=	4 * 32 * 1,
			[6] = { maxlen = 32 },
			maxlen = 6
		},
		nameMap = {
			'ImeiId',		-- [1] ( char )
			'WifiId',		-- [2] ( char )
			'ImsiId',		-- [3] ( char )
			'SimSerialNo',		-- [4] ( char )
			'SystemId',		-- [5] ( char )
			'nReserved',		-- [6] ( int )
		},
		formatKey = '<A5i32',
		deformatKey = '<A32A32A32A32A32i32',
		maxsize = 288
	},
	
	KPI_CLIENT_DATA={
		lengthMap = {
			-- [1] = UserId( int )	: maxsize = 4,
			-- [2] = GameId( int )	: maxsize = 4,
													-- GameCode	: maxsize = 16	=	1 * 16 * 1,
			[3] = 16,
			-- [4] = ExeMajorVer( int )	: maxsize = 4,
			-- [5] = ExeMinorVer( int )	: maxsize = 4,
			-- [6] = ExeBuildno( int )	: maxsize = 4,
			-- [7] = RecomGameId( int )	: maxsize = 4,
													-- RecomGameCode	: maxsize = 16	=	1 * 16 * 1,
			[8] = 16,
			-- [9] = RecomExeMajorVer( int )	: maxsize = 4,
			-- [10] = RecomExeMinorVer( int )	: maxsize = 4,
			-- [11] = RecomExeBuildno( int )	: maxsize = 4,
			-- [12] = GroupId( int )	: maxsize = 4,
			-- [13] = Channel( int )	: maxsize = 4,
													-- HardId	: maxsize = 32	=	1 * 32 * 1,
			[14] = 32,
													-- MobileHardInfo	: 				maxsize = 288,
			[15] = { refered = 'KPIMBHardInfo', complexType = 'link_refer' },
			-- [16] = PkgType( int )	: maxsize = 4,
													-- CUID	: maxsize = 36	=	1 * 36 * 1,
			[17] = 36,
													-- nReserved	: maxsize = 128	=	4 * 32 * 1,
			[18] = { maxlen = 32 },
			-- [19] = dwRecordTime( unsigned long )	: maxsize = 4,
			maxlen = 19
		},
		nameMap = {
			'UserId',		-- [1] ( int )
			'GameId',		-- [2] ( int )
			'GameCode',		-- [3] ( char )
			'ExeMajorVer',		-- [4] ( int )
			'ExeMinorVer',		-- [5] ( int )
			'ExeBuildno',		-- [6] ( int )
			'RecomGameId',		-- [7] ( int )
			'RecomGameCode',		-- [8] ( char )
			'RecomExeMajorVer',		-- [9] ( int )
			'RecomExeMinorVer',		-- [10] ( int )
			'RecomExeBuildno',		-- [11] ( int )
			'GroupId',		-- [12] ( int )
			'Channel',		-- [13] ( int )
			'HardId',		-- [14] ( char )
			'MobileHardInfo',		-- [15] ( refer )
			'PkgType',		-- [16] ( int )
			'CUID',		-- [17] ( char )
			'nReserved',		-- [18] ( int )
			'dwRecordTime',		-- [19] ( unsigned long )
		},
		formatKey = '<i2Ai4Ai5A6i33Ai32L',
		deformatKey = '<i2A16i4A16i5A32A32A32A32A32A32i33A36i32L',
		maxsize = 568
	},
    UP_PLAYER={
        lengthMap = {
			-- [1] = nUserID( int )	: maxsize = 4,
			-- [2] = nRoomID( int )	: maxsize = 4,
			-- [3] = nTableNo( int )	: maxsize = 4,
			-- [4] = nChairNo( int )	: maxsize = 4,
			-- [5] = nGameID( int )	: maxsize = 4,
			-- [6] = nDestID( int )	: maxsize = 4,
			-- [7] = nDestChairNo( int )	: maxsize = 4,
													-- szUserName	: maxsize = 32	=	1 * 32 * 1,
			[8] = 32,
													-- nReserved	: maxsize = 16	=	4 * 4 * 1,
			[9] = { maxlen = 4 },
													-- kpiClientData	: 				maxsize = 568,
			[10] = { refered = 'KPI_CLIENT_DATA', complexType = 'link_refer' },
			maxlen = 10
		},
		nameMap = {
			'nUserID',		-- [1] ( int )
			'nRoomID',		-- [2] ( int )
			'nTableNO',		-- [3] ( int )
			'nChairNO',		-- [4] ( int )
			'nGameID',		-- [5] ( int )
			'nDestID',		-- [6] ( int )
			'nDestChairNO',		-- [7] ( int )
			'szDestName',		-- [8] ( char )
			'nReserved',		-- [9] ( int )
			'kpiClientData',		-- [10] ( refer )
		},
		formatKey = '<i7Ai6Ai4Ai5A6i33Ai32L',
		deformatKey = '<i7A32i6A16i4A16i5A32A32A32A32A32A32i33A36i32L',
		maxsize = 644
	},

    UpPlayerRes={
                lengthMap = {
            [8] = {maxlen = 4},
            maxlen = 8
        },
        nameMap = {
            'nSourceChairNO',
            'nDestChairNO',
            'nUpCount',
            'nCurUpCount',
            'nMaxUpCount',
            'nUpState',
            'bUpSucceed',
            'nReserved'
        },
        formatKey = '<iiiiiiiiiii',
        deformatKey = '<iiiiiiiiiii',
        maxsize = 44
    },

    UpInfo={
        lengthMap = {
            [4] = {maxlen = 4},
            maxlen = 4
        },
        nameMap = {
            'nUserID',
            'nDestID',
            'nDestChairNO',
            'nReserved'
        },
        formatKey = '<iiiiiii',
        deformatKey = '<iiiiiii',
        maxsize = 28
    },
    UpInfoRes={
        lengthMap = {
            [8] = {maxlen = 4},
            maxlen = 8
        },
        nameMap = {
            'nUserID',
            'nCurUpCount',
            'nDestID',
            'nDestChairNO',
            'nUpedCount',
            'nMaxUpCount',
            'nUpState',
            'nReserved'
        },
        formatKey = '<iiiiiiiiiii',
        deformatKey = '<iiiiiiiiiii',
        maxsize = 44
    },
    CONTINUALWININFO={
        lengthMap = {
            maxlen = 6
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nContinualWinCount',
            'bWin'
        },
        formatKey = '<iiiiii',
        deformatKey = '<iiiiii',
        maxsize = 24
    },
    CHECK_OFFLINE={
        lengthMap = {
            maxlen = 4
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO'
        },
        formatKey = '<iiii',
        deformatKey = '<iiii',
        maxsize = 16
    },
    UPDATE_DEPOSIT_TABLE={
        lengthMap = {
            maxlen = 6
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nDepositDiff',
            'nDeposit'
        },
        formatKey = '<iiiiii',
        deformatKey = '<iiiiii',
        maxsize = 24
    },
    BUY_PROPS_THROW={
        lengthMap = {
			-- [1] = nUserID( int )	: maxsize = 4,
			-- [2] = nRoomID( int )	: maxsize = 4,
			-- [3] = nTableNO( int )	: maxsize = 4,
			-- [4] = nChairNO( int )	: maxsize = 4,
			-- [5] = nDestUserID( int )	: maxsize = 4,
			-- [6] = nDestChairNO( int )	: maxsize = 4,
			-- [7] = nPropID( int )	: maxsize = 4,
			-- [8] = nOSType( int )	: maxsize = 4,
													-- szUserName	: maxsize = 32	=	1 * 32 * 1,
			[9] = 32,
			-- [10] = nCurrentCount( int )	: maxsize = 4,
													-- kpiClientData	: 				maxsize = 568,
			[11] = { refered = 'KPI_CLIENT_DATA', complexType = 'link_refer' },
			maxlen = 11
		},
		nameMap = {
			'nUserID',		-- [1] ( int )
			'nRoomID',		-- [2] ( int )
			'nTableNO',		-- [3] ( int )
			'nChairNO',		-- [4] ( int )
			'nDestUserID',		-- [5] ( int )
			'nDestChairNO',		-- [6] ( int )
			'nPropID',		-- [7] ( int )
			'nOSType',		-- [8] ( int )
			'szUserName',		-- [9] ( char )
			'nCurrentCount',		-- [10] ( int )
			'kpiClientData',		-- [11] ( refer )
		},
		formatKey = '<i8Ai3Ai4Ai5A6i33Ai32L',
		deformatKey = '<i8A32i3A16i4A16i5A32A32A32A32A32A32i33A36i32L',
		maxsize = 636
	},
    BUY_PROP_RESP={
        lengthMap = {
            maxlen = 5
        },
        nameMap = {
            'nSourceChairNO',
            'nDestChairNO',
            'nCurrentCount',
            'nMaxCount',
            'nState'
        },
        formatKey = '<iiiii',
        deformatKey = '<iiiii',
        maxsize = 20
    },
    EXCHANGE_ROUND_INFO={
        lengthMap = {
            maxlen = 3
        },
        nameMap = {
            'nUserID',
            'nExchangeRoundNum',
            'nMaxRoundNum'
        },
        formatKey = '<iii',
        deformatKey = '<iii',
        maxsize = 12
    },
    FINISH_EXCHANGE_ROUND_INFO={
        lengthMap = {
            maxlen = 6
        },
        nameMap = {
            'nUserID',
            'nRoomID',
            'nTableNO',
            'nChairNO',
            'nPrizeType',
            'nPrizeNum'
        },
        formatKey = '<iiiiii',
        deformatKey = '<iiiiii',
        maxsize = 24
    },
	GAME_RESULT_EXCHANGE_INFO={
		lengthMap = {
			-- [1] = nCurrentBount( int )	: maxsize = 4,
			-- [2] = nTargetBout( int )	: maxsize = 4,
			-- [3] = nTodayVochers( int )	: maxsize = 4,
			-- [4] = nRewardNums( int )	: maxsize = 4,
			-- [5] = nNeedReward( int )	: maxsize = 4,
			maxlen = 5
		},
		nameMap = {
			'nCurrentBount',		-- [1] ( int )
			'nTargetBout',		-- [2] ( int )
			'nTodayVochers',		-- [3] ( int )
			'nRewardNums',		-- [4] ( int )
			'nNeedReward',		-- [5] ( int )
		},
		formatKey = '<i5',
		deformatKey = '<i5',
		maxsize = 20
	},
    GAME_NATIONAL_ACTIVITY={
		lengthMap = {
			-- [1] = nTodayScore( int )	: maxsize = 4,
			-- [2] = nBaseScore( int )	: maxsize = 4,
			-- [3] = nFactor( int )	: maxsize = 4,
			maxlen = 3
		},
		nameMap = {
			'nTodayScore',		-- [1] ( int )
			'nBaseScore',		-- [2] ( int )
			'nFactor',		-- [3] ( int )
		},
		formatKey = '<i3',
		deformatKey = '<i3',
		maxsize = 12
	},
	NOTIFY_PLAYERINFO_REQ={
		lengthMap = {
			-- [1] = nUserID( int )	: maxsize = 4,
			-- [2] = nTableNo( int )	: maxsize = 4,
			-- [3] = nRoomID( int )	: maxsize = 4,
													-- szPlayerChannel	: maxsize = 32	=	1 * 32 * 1,
			[4] = 32,
													-- szVersion	: maxsize = 32	=	1 * 32 * 1,
			[5] = 32,
													-- szNickName	: maxsize = 32	=	1 * 32 * 1,
			[6] = 32,
			-- [7] = nSafeDeposit( int )	: maxsize = 4,
													-- szPhone	: maxsize = 32	=	1 * 32 * 1,
			[8] = 32,
													-- nReserved	: maxsize = 16	=	4 * 4 * 1,
			[9] = { maxlen = 4 },
			maxlen = 9
		},
		nameMap = {
			'nUserID',		-- [1] ( int )
			'nTableNo',		-- [2] ( int )
			'nRoomID',		-- [3] ( int )
			'szPlayerChannel',		-- [4] ( char )
			'szVersion',		-- [5] ( char )
			'szNickName',		-- [6] ( char )
			'nSafeDeposit',		-- [7] ( int )
			'szPhone',		-- [8] ( char )
			'nReserved',		-- [9] ( int )
		},
		formatKey = '<i3A3iAi4',
		deformatKey = '<i3A32A32A32iA32i4',
		maxsize = 160
	},
	FiveBoomDoubleOpen={
		lengthMap = {
			-- [1] = nFiveBoomDoubleOpen( int )	: maxsize = 4,
			maxlen = 1
		},
		nameMap = {
			'nFiveBoomDoubleOpen',		-- [1] ( int )
		},
		formatKey = '<i',
		deformatKey = '<i',
		maxsize = 4
	},
	THROW_EXPRESSION={
		lengthMap = {
			-- [1] = nUserID( int )	: maxsize = 4,
			-- [2] = nRoomID( int )	: maxsize = 4,
			-- [3] = nTableNO( int )	: maxsize = 4,
			-- [4] = nChairNO( int )	: maxsize = 4,
			-- [5] = nExpressionIndex( int )	: maxsize = 4,
			-- [6] = nOSType( int )	: maxsize = 4,
													-- nReserver	: maxsize = 16	=	4 * 4 * 1,
			[7] = { maxlen = 4 },
			maxlen = 7
		},
		nameMap = {
			'nUserID',		-- [1] ( int )
			'nRoomID',		-- [2] ( int )
			'nTableNO',		-- [3] ( int )
			'nChairNO',		-- [4] ( int )
			'nExpressionIndex',		-- [5] ( int )
			'nOSType',		-- [6] ( int )
			'nReserver',		-- [7] ( int )
		},
		formatKey = '<i10',
		deformatKey = '<i10',
		maxsize = 40
	},

	UPDATE_TIMING_GAME_TABLE={
		lengthMap = {
			-- [1] = nUserID( int )	: maxsize = 4,
			-- [2] = nRoomID( int )	: maxsize = 4,
			-- [3] = nTableNO( int )	: maxsize = 4,
			-- [4] = nChairNO( int )	: maxsize = 4,
			-- [5] = nScore( int )	: maxsize = 4,
													-- nReserved	: maxsize = 16	=	4 * 4 * 1,
			[6] = { maxlen = 4 },
			maxlen = 6
		},
		nameMap = {
			'nUserID',		-- [1] ( int )
			'nRoomID',		-- [2] ( int )
			'nTableNO',		-- [3] ( int )
			'nChairNO',		-- [4] ( int )
			'nScore',		-- [5] ( int )
			'nReserved',		-- [6] ( int )
		},
		formatKey = '<i9',
		deformatKey = '<i9',
		maxsize = 36
	},
}
cc.load('treepack').resolveReference(MyGameReq)
return MyGameReq