local ValuablePurchaseDef = {
    GR_VALUABLE_PURCHASE_QUERY_INFO = 404500, -- 请求详情
    GR_VALUABLE_PURCHASE_START_PAY = 404501, -- 请求购买
    GR_VALUABLE_PURCHASE_PAY_RESULT = 404502, -- 发放奖励

    VALUABLE_PURCHASE_ITEMTYPE_SILVER = 1, -- 银子
    VALUABLE_PURCHASE_ITEMTYPE_EXCHANGE = 2, -- 礼券
    VALUABLE_PURCHASE_ITEMTYPE_PROP = 3, -- 道具

    REWARD_PROP_ID_ONEDAY_CARD_MARKER       = 3, -- 道具ID：1天记牌器
    REWARD_PROP_ID_7DAY_CARD_MARKER         = 4, -- 道具ID：7天记牌器
    REWARD_PROP_ID_30DAY_CARD_MARKER        = 5, -- 道具ID：30天记牌器
    REWARD_PROP_ID_EXPRESSION_ROSE          = 6, -- 道具ID：表情玫瑰
    REWARD_PROP_ID_EXPRESSION_LIGHTNING     = 7, -- 道具ID：表情闪电
    REWARD_PROP_ID_ONEBOUT_CARDMARKER       = 8, -- 道具ID：单局记牌器
    REWARD_PROP_ID_TIMING_GAME_TICKET       = 17, -- 道具ID：定时赛门票


    VALUABLE_PURCHASE_QUERY_INFO_OK = 0,
    VALUABLE_PURCHASE_QUERY_INFO_PLATFORM_ERROR = 1,
    VALUABLE_PURCHASE_QUERY_INFO_NPLEVEL_ERROR = 2,
    VALUABLE_PURCHASE_QUERY_INFO_DISABLE = 3,

    VALUABLE_PURCHASE_START_PAY_OK = 0, -- 可以购买此项
    VALUABLE_PURCHASE_START_PAY_ALLREADY_PAYED = 1, -- 此项已购买
    VALUABLE_PURCHASE_START_PAY_PLATFORM_ERROR = 2, -- 购买平台错误
    VALUABLE_PURCHASE_START_PAY_NO_THIS_PURCHASE = 3, -- 没有此购买项
    VALUABLE_PURCHASE_START_PAY_CLIENT_DATE_ERROR = 4, -- 客户端时间不正确
    VALUABLE_PURCHASE_START_PAY_SYSTEM_ERROR = 5, -- redis出错

    VALUABLE_PURCHASE_PAY_RESULT_OK = 0,
    VALUABLE_PURCHASE_PAY_RESULT_NO_INPAYING_PURCHASE = 1,
}

return ValuablePurchaseDef
